language: d

install:
- export TRAVIS_OS_NAME=linux
- curl "https://api.github.com/repos/ColdenCullen/doveralls/releases" | jq '.[0].assets | .[] | select(.name == "doveralls_linux_travis") | .browser_download_url' | xargs wget -O doveralls
- chmod +x doveralls

script:
- dub test -b unittest-cov mlfe:mapleparser
- ./doveralls
