language: d

install:
- export TRAVIS_OS_NAME=linux
- wget -O doveralls "https://github.com/ColdenCullen/doveralls/releases/download/v1.2.0/doveralls_linux_travis"
- chmod +x doveralls

script:
- dub test -b unittest-cov mlfe:mapleparser
- ./doveralls
