language: d

install:
- wget -q -O - "http://bit.ly/Doveralls" > doveralls_script.sh
- cat doveralls_script.sh
- bash ./doveralls_script.sh
- chmod +x doveralls

script:
- dub test -b unittest-cov mlfe:mapleparser
- ./doveralls
