language: d

install:
- export TRAVIS_OS_NAME=linux
- wget -q -O - "http://bit.ly/Doveralls" > doveralls.install.sh
- bash ./doveralls.install.sh
- chmod +x doveralls

script:
- dub test -b unittest-cov mlfe:mapleparser
- ./doveralls
